image: "ruby:2.3"

services:
  - postgres:latest
  - redis:alpine

stages:
  - lint
  - test
  - registry

variables:
  POSTGRES_DB: stronghold_test
  POSTGRES_USER: stronghold
  POSTGRES_PASSWORD: stronghold
  RAILS_ENV: test

before_script:
  - sh ./scripts/install-node.sh
  - gem install bundler         # Bundler is not installed with the image
  - gem install rubocop         # Install rubocop globally
  - bundle install -j $(nproc)  # Install dependencies
  - rake db:migrate
  - rake db:seed

after_script:
  - rake db:drop

rubocop:
  stage: lint
  script:
  - rubocop
  tags:
  - docker

rspec:
  stage: test
  variables:
    POSTGRES_URI: 'postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB'
    REDIS_CACHE_URI: 'redis://redis:6379/0/cache'
    REDIS_SESSION_URI: 'redis://redis:6379/0/session'
  script:
  - bundle exec rspec
  tags:
  - docker

build:image:
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/joaoevangelista/stronghold .
    - docker push registry.gitlab.com/joaoevangelista/stronghold:$CI_BUILD_TAG
  tags:
    - docker
  only:
    - tags
  when: on_success
