# A docker composer file for easy start of the required services
version: '2'
services:
  redis:
    ports:
    - '6379:6379'
    image: redis:alpine
  postgres:
    image: postgres:latest
    # This will create databases for testing and development
    command: bash -c 'createdb stronghold_dev && createdb stronghold_test'
    ports:
     - '5432:5432'
    environment:
     POSTGRES_PASSWORD: devpassword
     POSTGRES_USER: stronghold
